my_blog/home/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.urls import reverse_lazy

from home import views

app_name = "home"
urlpatterns = [
    path("", views.index, name="index"),
    path('about/', views.about_page, name='about'),
    path("search/", views.search, name="search"),
    path('avatar/load', views.avatar_load, name='avatar-load'),
    path("register/", views.register, name="user-register"),
    path('register/update/', views.user_update, name='user-update'),
    path(
        'password_change/',
        auth_views.PasswordChangeView.as_view(
            template_name='registration/change-password.html',
            success_url=reverse_lazy("home:password-change-done")
        ),
        name="password-change"
    ),
    path(
        'password_change/done/',
        auth_views.PasswordChangeDoneView.as_view(
            template_name='registration/change-password-done.html'
        ),
        name="password-change-done"
    ),
]

my_blog/my_blog/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path("course/", include("course.urls")),
    path("student/", include("student.urls")),
    path("profesor/", include("profesor.urls")),
]

if settings.DEBUG:
     from django.conf.urls.static import static
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_blog/student/urls.py
from django.urls import path

from student import views

app_name = "student"
urlpatterns = [
    path("students", views.StudentListView.as_view(), name="student-list"),
    path("student/add/", views.StudentCreateView.as_view(), name="student-add"),
    path("student/<int:pk>/detail/", views.StudentDetailView.as_view(), name="student-detail"),
    path("student/<int:pk>/update/", views.StudentUpdateView.as_view(), name="student-update"),
    path("student/<int:pk>/delete/", views.StudentDeleteView.as_view(), name="student-delete"),
]

my_blog/student/models.py
from django.db import models

class Student(models.Model):
    name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=40)
    email = models.EmailField()

    def __str__(self):
        return f"{self.name} {self.last_name} | email: {self.email}"

my_blog/student/forms.py
from django import forms

from student.models import Student

class StudentForm(forms.ModelForm):
    name = forms.CharField(
        label="Nombre del estudiante",
        max_length=40,
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "student-name",
                "placeholder": "Nombre del estudiante",
                "required": "True",
            }
        ),
    )
    last_name = forms.CharField(
        label="Apellido del estudiante",
        max_length=40,
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "student-last-name",
                "placeholder": "Apellido del estudiante",
                "required": "True",
            }
        ),
    )
    email = forms.EmailField(
        label="Email:",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "student-email",
                "placeholder": "email",
                "required": "True",
            }
        ),
    )

    class Meta:
        model = Student
        fields = ["name", "last_name", "email"]

my_blog/student/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from student.models import Student
from student.forms import StudentForm


class StudentListView(ListView):
    model = Student
    paginate_by = 3


class StudentDetailView(DetailView):
    model = Student
    fields = ["name", "last_name", "email"]


class StudentCreateView(LoginRequiredMixin, CreateView):
    model = Student
    success_url = reverse_lazy("student:student-list")

    form_class = StudentForm

    def form_valid(self, form):
        """Filter to avoid duplicate students"""
        data = form.cleaned_data
        actual_objects = Student.objects.filter(
            name=data["name"],
            last_name=data["last_name"],
            email=data["email"],
        ).count()
        if actual_objects:
            messages.error(
                self.request,
                f"El Estudiente {data['name']} {data['last_name']} | {data['email']} ya está creado",
            )
            form.add_error("name", ValidationError("Acción no válida"))
            return super().form_invalid(form)
        else:
            messages.success(
                self.request,
                f"Estudiente: {data['name']} - {data['last_name']}. Creado exitosamente!",
            )
            return super().form_valid(form)


class StudentUpdateView(LoginRequiredMixin, UpdateView):
    model = Student
    fields = ["name", "last_name", "email"]

    def get_success_url(self):
        student_id = self.kwargs["pk"]
        return reverse_lazy("student:student-detail", kwargs={"pk": student_id})


class StudentDeleteView(LoginRequiredMixin, DeleteView):
    model = Student
    success_url = reverse_lazy("student:student-list")

my_blog/student/templates/student/student_confirm_delete.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Student delete
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/post-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h1>{{ student.name }}</h1>
                    <span class="subheading">Eliminar Estudiente</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}


{% block my_blog_content %}

<h1>Estás seguro de eliminar el Estudiente: {{ student.name }}?</h1>

<form action="" method="POST">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="Si, eliminar.">
    <a class="btn btn-primary" href="{% url 'student:student-list' %}" >Cancelar</a>
</form>

{% endblock %}

my_blog/student/templates/student/student_detail.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Student detail
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/post-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h1>{{ student.name }} {{ student.last_name }}</h1>
                    <span class="subheading">Detalles del student</span>
                </div>
            </div>
        </div>
        <a class="button_custom" href="{% url 'student:student-add' %}">Crear nuevo Estudiente</a>
    </div>
</header>
{% endblock %}


{% block my_blog_content %}
<!-- Post preview-->
<div class="post-preview">
    <h3 class="post-subtitle">Email: {{ student.email }}</h3>
    <p style="text-align: center">
        <a href="{% url 'student:student-update' student.id %}">
            <i class="fa fa-pencil" style="color: #1c1c91;"></i> Editar
        </a>
        &ensp; | &ensp;
        <a href="{% url 'student:student-delete' student.id %}">
            <i class="fa fa-trash" style="color: #881a1a;"></i> Eliminar 
        </a>
    </p>
</div>
{% endblock %}

my_blog/student/templates/student/student_form.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Student Create-Update
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/post-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h2>Formulario para guardar/editar estudiente</h2>
                    <span class="subheading">My blog CoderHouse</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block my_blog_content %}
    <div>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="Guardar estudiente" />
        </form>
    </div>
    <!-- Divider-->
    <hr class="my-4" />
{% endblock %}

my_blog/student/templates/student/student_list.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Student
{% endblock %}

{% block my_blog_header %}
    <header class="masthead" style="background-image: url('/static/home/assets/img/post-bg.jpg')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-15 col-lg-16 col-xl-14">
                    <div class="site-heading">
                        <h1>Listado de Estudiantes</h1>
                        <span class="subheading">Blog Interno de Profesores</span>
                    </div>
                </div>
            </div>
            <a class="button_custom" href="{% url 'student:student-add' %}">Crear nuevo Estudiente</a>
        </div>
    </header>
{% endblock %}

{% block my_blog_content %}
    {% for student in student_list %}
        <!-- Post preview-->
        <div class="post-preview">
            <a href="{% url 'student:student-detail' student.id %}">
                <h2 class="post-title">Student: {{ student.name }}  {{ student.last_name }}</h2>
                <h3 class="post-subtitle">Email: {{ student.email }}</h3>
            </a>
        </div>
        <!-- Divider-->
        <hr class="my-4" />
    {% endfor %}
{% endblock %}