my_blog/home/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.urls import reverse_lazy

from home import views

app_name = "home"
urlpatterns = [
    path("", views.index, name="index"),
    path('about/', views.about_page, name='about'),
    path("search/", views.search, name="search"),
    path('avatar/load', views.avatar_load, name='avatar-load'),
    path("register/", views.register, name="user-register"),
    path('register/update/', views.user_update, name='user-update'),
    path(
        'password_change/',
        auth_views.PasswordChangeView.as_view(
            template_name='registration/change-password.html',
            success_url=reverse_lazy("home:password-change-done")
        ),
        name="password-change"
    ),
    path(
        'password_change/done/',
        auth_views.PasswordChangeDoneView.as_view(
            template_name='registration/change-password-done.html'
        ),
        name="password-change-done"
    ),
]

my_blog/my_blog/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path("course/", include("course.urls")),
    path("student/", include("student.urls")),
    path("profesor/", include("profesor.urls")),
]

if settings.DEBUG:
     from django.conf.urls.static import static
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_blog/profesor/urls.py
from django.urls import path

from profesor import views

app_name = "profesor"
urlpatterns = [
    path("profesors", views.ProfesorListView.as_view(), name="profesor-list"),
    path("profesor/add/", views.ProfesorCreateView.as_view(), name="profesor-add"),
    path("profesor/<int:pk>/detail/", views.ProfesorDetailView.as_view(), name="profesor-detail"),
    path("profesor/<int:pk>/update/", views.ProfesorUpdateView.as_view(), name="profesor-update"),
    path("profesor/<int:pk>/delete/", views.ProfesorDeleteView.as_view(), name="profesor-delete"),
]

my_blog/profesor/models.py
from django.db import models


class Profesor(models.Model):
    name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=40)
    email = models.EmailField()
    profession = models.CharField(max_length=40)

    def __str__(self):
        return f"{self.name} {self.last_name}"

my_blog/profesor/forms.py
from django import forms

from profesor.models import Profesor

class ProfesorForm(forms.ModelForm):
    name = forms.CharField(
        label="Nombre del profesor",
        max_length=40,
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "profesor-name",
                "placeholder": "Nombre del profesor",
                "required": "True",
            }
        ),
    )
    last_name = forms.CharField(
        label="Apellido del profesor",
        max_length=40,
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "profesor-last-name",
                "placeholder": "Apellido del profesor",
                "required": "True",
            }
        ),
    )
    email = forms.EmailField(
        label="Email:",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "profesor-email",
                "placeholder": "email",
                "required": "True",
            }
        ),
    )
    profession = forms.CharField(
        label="Profesión:",
        max_length=40,
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "profesor-profession",
                "placeholder": "Profesión",
                "required": "True",
            }
        ),
    )

    class Meta:
        model = Profesor
        fields = ["name", "last_name", "email", "profession"]

my_blog/profesor/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from profesor.models import Profesor
from profesor.forms import ProfesorForm


class ProfesorListView(ListView):
    model = Profesor
    paginate_by = 3


class ProfesorDetailView(DetailView):
    model = Profesor
    fields = ["name", "last_name", "email", "profession"]


class ProfesorCreateView(LoginRequiredMixin, CreateView):
    model = Profesor
    success_url = reverse_lazy("profesor:profesor-list")

    form_class = ProfesorForm

    def form_valid(self, form):
        """Filter to avoid duplicate profesors"""
        data = form.cleaned_data
        actual_objects = Profesor.objects.filter(
            name=data["name"],
            last_name=data["last_name"],
            email=data["email"],
        ).count()
        if actual_objects:
            messages.error(
                self.request,
                f"El Profesor {data['name']} {data['last_name']} | {data['email']} ya está creado",
            )
            form.add_error("name", ValidationError("Acción no válida"))
            return super().form_invalid(form)
        else:
            messages.success(
                self.request,
                f"Profesor: {data['name']} - {data['last_name']}. Creado exitosamente!",
            )
            return super().form_valid(form)


class ProfesorUpdateView(LoginRequiredMixin, UpdateView):
    model = Profesor
    fields = ["name", "last_name", "email", "profession"]

    def get_success_url(self):
        profesor_id = self.kwargs["pk"]
        return reverse_lazy("profesor:profesor-detail", kwargs={"pk": profesor_id})


class ProfesorDeleteView(LoginRequiredMixin, DeleteView):
    model = Profesor
    success_url = reverse_lazy("profesor:profesor-list")

my_blog/profesor/templates/profesor/profesor_confirm_delete.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Profesor delete
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/post-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h1>{{ profesor.name }}</h1>
                    <span class="subheading">Eliminar Profesor</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}


{% block my_blog_content %}

<h1>Estás seguro de eliminar el Profesor: {{ profesor.name }}?</h1>

<form action="" method="POST">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="Si, eliminar.">
    <a class="btn btn-primary" href="{% url 'profesor:profesor-list' %}" >Cancelar</a>
</form>

{% endblock %}

my_blog/profesor/templates/profesor/profesor_detail.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Profesor detail
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/post-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h1>{{ profesor.name }} {{ profesor.last_name }}</h1>
                    <span class="subheading">Detalles del profesor</span>
                </div>
            </div>
        </div>
        <a class="button_custom" href="{% url 'profesor:profesor-add' %}">Crear nuevo Profesor</a>
    </div>
</header>
{% endblock %}


{% block my_blog_content %}
<!-- Post preview-->
<div class="post-preview">
    <h3 class="post-subtitle">Email: {{ profesor.email }}</h3>
    <h3 class="post-subtitle">Profesión: {{ profesor.profession }}</h3>
    <p style="text-align: center">
        <a href="{% url 'profesor:profesor-update' profesor.id %}">
            <i class="fa fa-pencil" style="color: #1c1c91;"></i> Editar
        </a>
        &ensp; | &ensp;
        <a href="{% url 'profesor:profesor-delete' profesor.id %}">
            <i class="fa fa-trash" style="color: #881a1a;"></i> Eliminar 
        </a>
    </p>
</div>
{% endblock %}

my_blog/profesor/templates/profesor/profesor_form.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Profesor Create-Update
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/post-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h2>Formulario para guardar/editar profesor</h2>
                    <span class="subheading">My blog CoderHouse</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block my_blog_content %}
    <div>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="Guardar profesor" />
        </form>
    </div>
    <!-- Divider-->
    <hr class="my-4" />
{% endblock %}

my_blog/profesor/templates/profesor/profesor_list.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Profesor
{% endblock %}

{% block my_blog_header %}
    <header class="masthead" style="background-image: url('/static/home/assets/img/post-bg.jpg')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-15 col-lg-16 col-xl-14">
                    <div class="site-heading">
                        <h1>Listado de Profesores</h1>
                        <span class="subheading">Blog Interno de Profesores</span>
                    </div>
                </div>
            </div>
            <a class="button_custom" href="{% url 'profesor:profesor-add' %}">Crear nuevo Profesor</a>
        </div>
    </header>
{% endblock %}

{% block my_blog_content %}
    {% for profesor in profesor_list %}
        <!-- Post preview-->
        <div class="post-preview">
            <a href="{% url 'profesor:profesor-detail' profesor.id %}">
                <h2 class="post-title">Profesor: {{ profesor.name }}  {{ profesor.last_name }}</h2>
                <h3 class="post-subtitle">Email: {{ profesor.email }}</h3>
                <h3 class="post-subtitle">Profesión: {{ profesor.profession }}</h3>
            </a>
        </div>
        <!-- Divider-->
        <hr class="my-4" />
    {% endfor %}
{% endblock %}