my_blog/course/urls.py
from django.urls import path

from course import views

app_name = "course"
urlpatterns = [
    path("courses/", views.CourseListView.as_view(), name="course-list"),
    path("course/add/", views.CourseCreateView.as_view(), name="course-add"),
    path("course/<int:pk>/detail/", views.CourseDetailView.as_view(), name="course-detail"),
    path("course/<int:pk>/update/", views.CourseUpdateView.as_view(), name="course-update"),
    path("course/<int:pk>/delete/", views.CourseDeleteView.as_view(), name="course-delete"),
    path("comment/<int:pk>/add/", views.CommentCreateView.as_view(), name="comment-create"),
    path("comment/<int:pk>/delete/", views.CommentDeleteView.as_view(), name="comment-delete"),

    path("homeworks", views.HomeworkListView.as_view(), name="homework-list"),
    path("homework/add/", views.HomeworkCreateView.as_view(), name="homework-add"),
    path("homework/<int:pk>/detail/", views.HomeworkDetailView.as_view(), name="homework-detail"),
    path("homework/<int:pk>/update/", views.HomeworkUpdateView.as_view(), name="homework-update"),
    path("homework/<int:pk>/delete/", views.HomeworkDeleteView.as_view(), name="homework-delete"),
]

my_blog/home/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.urls import reverse_lazy

from home import views

app_name = "home"
urlpatterns = [
    path("", views.index, name="index"),
    path('about/', views.about_page, name='about'),
    path("search/", views.search, name="search"),
    path('avatar/load', views.avatar_load, name='avatar-load'),
    path("register/", views.register, name="user-register"),
    path('register/update/', views.user_update, name='user-update'),
    path(
        'password_change/',
        auth_views.PasswordChangeView.as_view(
            template_name='registration/change-password.html',
            success_url=reverse_lazy("home:password-change-done")
        ),
        name="password-change"
    ),
    path(
        'password_change/done/',
        auth_views.PasswordChangeDoneView.as_view(
            template_name='registration/change-password-done.html'
        ),
        name="password-change-done"
    ),
]

my_blog/my_blog/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path("course/", include("course.urls")),
    path("student/", include("student.urls")),
    path("profesor/", include("profesor.urls")),
]

if settings.DEBUG:
     from django.conf.urls.static import static
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_blog/course/models.py
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator
from django.db import models
from ckeditor.fields import RichTextField


class Course(models.Model):
    name = models.CharField(max_length=40, null=False, blank=False)
    code = models.IntegerField(null=False, blank=False)
    description = RichTextField(null=True, blank=True)
    image = models.ImageField(upload_to='course', null=True, blank=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    comments = models.ManyToManyField(
        User, through="Comment", related_name="comments_owned"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = (
            "name",
            "code",
        )
        ordering = ["-created_at"]

    def __str__(self):
        return f"Course: {self.name} | code: {self.code}"


class Comment(models.Model):
    text = models.TextField(
        validators=[
            MinLengthValidator(10, "El comentario debe ser mayor de 10 caracteres")
        ]
    )
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Homework(models.Model):
    name = models.CharField(max_length=40)
    due_date = models.DateField()
    is_delivered = models.BooleanField()

    def __str__(self):
        is_delivered = "Si" if self.is_delivered else "No"
        return f"{self.name} | fecha: {self.due_date} | Engregado: {is_delivered}"

my_blog/course/forms.py
from ckeditor.widgets import CKEditorWidget
from django import forms

from course.models import Course
from course.models import Homework


class CourseForm(forms.ModelForm):
    name = forms.CharField(
        label="Nombre del curso",
        max_length=40,
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "course-name",
                "placeholder": "Nombre de curso",
                "required": "True",
            }
        ),
    )

    code = forms.IntegerField(
        label="Código:",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "course-code",
                "placeholder": "Código del curso",
                "required": "True",
            }
        ),
    )

    description = forms.CharField(
        label="Descripción:",
        required=False,
        widget=CKEditorWidget(),
    )

    image = forms.ImageField()

    class Meta:
        model = Course
        fields = ["name", "code", "description", "image"]


class CommentForm(forms.Form):
    comment_text = forms.CharField(
        label="",
        required=False,
        max_length=500,
        min_length=10,
        strip=True,
        widget=forms.Textarea(
            attrs={
                "class": "comment-text",
                "placeholder": "Ingrese su comentario...",
                "required": "True",
                "max_length": 500,
                "min_length": 10,
                "rows": 2,
                "cols": 10,
                "style":"min-width: 100%",
            }
        ),
    )


class HomeworkForm(forms.ModelForm):
    name = forms.CharField(
        label="Nombre del entregable",
        max_length=40,
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "homework-name",
                "placeholder": "Nombre del entregable",
                "required": "True",
            }
        ),
    )

    due_date = forms.DateField(
        label="Vencimiento de la entrega:",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "homework-code",
                "placeholder": "Fecha yyyy-mm-dd",
                "required": "True",
            }
        ),
    )

    is_delivered = forms.BooleanField(
        label="Entregado:",
        required=False,
    )

    class Meta:
        model = Homework
        fields = ["name", "due_date", "is_delivered"]

my_blog/course/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from course.forms import CommentForm
from course.forms import CourseForm
from course.forms import HomeworkForm
from course.models import Comment
from course.models import Course
from course.models import Homework


class CourseListView(ListView):
    model = Course
    paginate_by = 3


class CourseDetailView(DetailView):
    model = Course
    template_name = "course/course_detail.html"
    fields = ["name", "code", "description"]

    def get(self, request, pk):
        course = Course.objects.get(id=pk)
        comments = Comment.objects.filter(course=course).order_by("-updated_at")
        comment_form = CommentForm()
        context = {
            "course": course,
            "comments": comments,
            "comment_form": comment_form,
        }
        return render(request, self.template_name, context)


class CourseCreateView(LoginRequiredMixin, CreateView):
    model = Course
    success_url = reverse_lazy("course:course-list")

    form_class = CourseForm
    # fields = ["name", "code", "description", "image"]

    def form_valid(self, form):
        """Filter to avoid duplicate courses"""
        data = form.cleaned_data
        form.instance.owner = self.request.user
        actual_objects = Course.objects.filter(
            name=data["name"], code=data["code"]
        ).count()
        if actual_objects:
            messages.error(
                self.request,
                f"El curso {data['name']} - {data['code']} ya está creado",
            )
            form.add_error("name", ValidationError("Acción no válida"))
            return super().form_invalid(form)
        else:
            messages.success(
                self.request,
                f"Curso {data['name']} - {data['code']} creado exitosamente!",
            )
            return super().form_valid(form)


class CourseUpdateView(LoginRequiredMixin, UpdateView):
    model = Course
    fields = ["name", "code", "description", "image"]

    def get_success_url(self):
        course_id = self.kwargs["pk"]
        return reverse_lazy("course:course-detail", kwargs={"pk": course_id})

    def post(self, request, *args, **kwargs):
   
        return super().post(request, *args, **kwargs)


class CourseDeleteView(LoginRequiredMixin, DeleteView):
    model = Course
    success_url = reverse_lazy("course:course-list")


class CommentCreateView(LoginRequiredMixin, CreateView):
    def post(self, request, pk):
        course = get_object_or_404(Course, id=pk)
        comment = Comment(
            text=request.POST["comment_text"], owner=request.user, course=course
        )
        comment.save()
        return redirect(reverse("course:course-detail", kwargs={"pk": pk}))


class CommentDeleteView(LoginRequiredMixin, DeleteView):
    model = Comment

    def get_success_url(self):
        course = self.object.course
        return reverse("course:course-detail", kwargs={"pk": course.id})


class HomeworkListView(ListView):
    model = Homework
    paginate_by = 4


class HomeworkCreateView(LoginRequiredMixin, CreateView):
    model = Homework
    success_url = reverse_lazy("course:homework-list")

    form_class = HomeworkForm

    def form_valid(self, form):
        """Filter to avoid duplicate homeworks"""
        data = form.cleaned_data
        actual_objects = Homework.objects.filter(name=data["name"]).count()
        if actual_objects:
            messages.error(
                self.request,
                f"El entregable {data['name']} ya está creado",
            )
            form.add_error("name", ValidationError("Acción no válida"))
            return super().form_invalid(form)
        else:
            messages.success(
                self.request,
                f"Entregable: {data['name']}. Creado exitosamente!",
            )
            return super().form_valid(form)


class HomeworkDetailView(DetailView):
    model = Homework
    fields = ["name", "due_date", "is_delivered"]


class HomeworkUpdateView(LoginRequiredMixin, UpdateView):
    model = Homework
    fields = ["name", "due_date", "is_delivered"]

    def get_success_url(self):
        homework_id = self.kwargs["pk"]
        return reverse_lazy("course:homework-detail", kwargs={"pk": homework_id})


class HomeworkDeleteView(LoginRequiredMixin, DeleteView):
    model = Homework
    success_url = reverse_lazy("course:homework-list")

my_blog/course/templates/course/comment_confirm_delete.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Comentario delete
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/about-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h1>Eliminar Comentario</h1>
                    <span class="subheading">Creado por: {{ comment.owner.first_name }} {{ comment.owner.last_name }}</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}


{% block my_blog_content %}

<h1>Estás seguro de eliminar el siguiente Comentario?</h1>
<p>{{ comment.text }}</p>

<form action="" method="POST">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="Si, eliminar.">
    <a class="btn btn-primary" href="{% url 'course:course-detail' comment.course.id %}" >Cancelar</a>
</form>

{% endblock %}

my_blog/course/templates/course/course_confirm_delete.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Course delete
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/about-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h1>{{ course.name }}</h1>
                    <span class="subheading">Eliminar Curso</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}


{% block my_blog_content %}

<h1>Estás seguro de eliminar el Curso: {{ course.name }}?</h1>

<form action="" method="POST">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="Si, eliminar.">
    <a class="btn btn-primary" href="{% url 'course:course-list' %}" >Cancelar</a>
</form>

{% endblock %}

my_blog/course/templates/course/course_detail.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Course detail
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/about-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h1>{{ course.name }}</h1>
                    <span class="subheading">Detalles del curso</span>
                </div>
            </div>
        </div>
        <a class="button_custom" href="{% url 'course:course-add' %}">Crear nuevo Curso</a>
    </div>
</header>
{% endblock %}


{% block my_blog_content %}
<!-- Post preview-->
<div class="post-preview">
    <h3 class="post-subtitle">Código: {{ course.code }}</h3>
    <p class="post-meta">
        Creado por
        <span style="color: #0b4956;" href="">{{ course.owner.username }}</span>
        ( {{ course.created_at }} )
        <br>
        Última fecha de actualización ( {{ course.updated_at }} )
    </p>

    <!-- Image -->
    {% if course.image %}
        <div style="text-align: center;">
            <img height="250px" src="{{ course.image.url }}">
        </div>
    {% endif %}

    <!-- Description -->
    <p class="card-text ">{{ course.description|safe }}</p> <!-- ckeditor-->

    <!-- Update-Delete link only for the owner -->
    {% if user == course.owner or user.is_superuser %}
        <p style="text-align: center">
            <a href="{% url 'course:course-update' course.id %}">
                <i class="fa fa-pencil" style="color: #1c1c91;"></i> Editar Curso
            </a>
            &ensp; | &ensp;
            <a href="{% url 'course:course-delete' course.id %}">
                <i class="fa fa-trash" style="color: #881a1a;"></i> Eliminar Curso
            </a>
        </p>
    {% endif %}
    
    <!-- Divider-->
    <hr class="my-4" />

    <!-- Comment creation -->
    <form method="POST" action="{% url 'course:comment-create' course.id %}">
        {% csrf_token %}
        {{ comment_form }}
    <input type="submit" value="Publicar comentario">
    </form>
    {% if not comments %}
        <p></p>
    {% endif %}

    <!-- Comments list -->
    {% for comment in comments %}
        <p> {{ comment.text }}
            ({{ comment.owner.username }} | {{ comment.updated_at }})
            {% if user == comment.owner or user.is_superuser %}
            <a href="{% url 'course:comment-delete' comment.id %}"><i class="fa fa-trash" style="color: #881a1a;"></i></a>
            {% endif %}
        </p>
    {% endfor %}
</div>
{% endblock %}

my_blog/course/templates/course/course_form.html
{% extends "home/index.html" %}
{% load static %}

<!-- ckeditor-->
{% block extrahead %}
<script>window.CKEDITOR_BASEPATH = '/static/ckeditor/ckeditor/';</script>
{{ block.super }}
{% endblock %}
<!-- ckeditor-->

{% block my_blog_title %}
Course Create-Update
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/about-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h2>Formulario para guardar/editar curso</h2>
                    <span class="subheading">My blog CoderHouse</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block my_blog_content %}
    <div>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }} <!-- ckeditor-->
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="Guardar curso" />
        </form>
    </div>
    <!-- Divider-->
    <hr class="my-4" />
{% endblock %}

my_blog/course/templates/course/course_list.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Course list
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/about-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h1>Listado de cursos</h1>
                    <span class="subheading">Blog Interno de Profesores</span>
                </div>
            </div>
        </div>
        <a class="button_custom" href="{% url 'course:course-add' %}">Crear nuevo Curso</a>
    </div>
</header>
{% endblock %}


{% block my_blog_content %}
    {% for course in course_list %}
        <!-- Post preview-->
        <div class="post-preview">
            <a href="{% url 'course:course-detail' course.id %}">
                <h2 class="post-title">Este es el curso de {{ course.name }}</h2>
                <h3 class="post-subtitle">Que tiene el código: {{ course.code }}</h3>
            </a>
            <p class="post-meta">
                Creado por
                <span style="color: #0b4956;" href="">{{ course.owner.username }}</span>
                ( {{ course.created_at }} )
            </p>
        </div>
        <!-- Divider-->
        <hr class="my-4" />
    {% endfor %}
{% endblock %}

my_blog/course/templates/course/homework_confirm_delete.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Homework delete
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/post-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h1>{{ homework.name }}</h1>
                    <span class="subheading">Eliminar Entregable</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}


{% block my_blog_content %}

<h1>Estás seguro de eliminar el Entregable: {{ homework.name }}?</h1>

<form action="" method="POST">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="Si, eliminar.">
    <a class="btn btn-primary" href="{% url 'course:homework-list' %}" >Cancelar</a>
</form>

{% endblock %}

my_blog/course/templates/course/homework_detail.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Homework detail
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/post-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h1>{{ homework.name }}</h1>
                    <span class="subheading">Detalles de la entrega</span>
                </div>
            </div>
        </div>
        <a class="button_custom" href="{% url 'course:homework-add' %}">Crear nuevo Entregable</a>
    </div>
</header>
{% endblock %}


{% block my_blog_content %}
<!-- Post preview-->
<div class="post-preview">
    <h3 class="post-subtitle">Vencimiento de la entrega {{ homework.due_date }}</h3>
    <h5>
        Entregado:
        {% if homework.is_delivered %}
            Si
        {% else %}
            No
        {% endif%}
    </h5>
    <p style="text-align: center">
        <a href="{% url 'course:homework-update' homework.id %}">
            <i class="fa fa-pencil" style="color: #1c1c91;"></i> Editar
        </a>
        &ensp; | &ensp;
        <a href="{% url 'course:homework-delete' homework.id %}">
            <i class="fa fa-trash" style="color: #881a1a;"></i> Eliminar 
        </a>
    </p>
</div>
{% endblock %}

my_blog/course/templates/course/homework_form.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Homework Create-Update
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/post-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h2>Formulario para guardar/editar engregables</h2>
                    <span class="subheading">My blog CoderHouse</span>
                </div>
            </div>
        </div>
        <a class="button_custom" href="{% url 'course:homework-add' %}">Crear nuevo Entregable</a>
    </div>
</header>
{% endblock %}

{% block my_blog_content %}
    <div>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="Guardar Entregable" />
        </form>
    </div>
    <!-- Divider-->
    <hr class="my-4" />
{% endblock %}

my_blog/course/templates/course/homework_list.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Homework
{% endblock %}

{% block my_blog_header %}
    <header class="masthead" style="background-image: url('/static/home/assets/img/post-bg.jpg')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-15 col-lg-16 col-xl-14">
                    <div class="site-heading">
                        <h1>Listado de Entregables</h1>
                        <span class="subheading">Blog Interno de Profesores</span>
                    </div>
                </div>
            </div>
            <a class="button_custom" href="{% url 'course:homework-add' %}">Crear nuevo Entregable</a>
    </div>
    </header>
{% endblock %}

{% block my_blog_content %}
    {% for homework in homework_list %}
        <!-- Post preview-->
        <div class="post-preview">
            <a href="{% url 'course:homework-detail' homework.id %}">
                <h2 class="post-title">Este es el entregable: {{ homework.name }}</h2>
                <h3 class="post-subtitle">Vencimiento de la entrega: {{ homework.due_date }}</h3>
            </a>
        </div>
        <!-- Divider-->
        <hr class="my-4" />
    {% endfor %}
{% endblock %}